"""add recording metadata and status fields

Revision ID: b68ddba4077d
Revises: f056e8abdc46
Create Date: 2026-10-05 17:41:15.092955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68ddba4077d'
down_revision: Union[str, Sequence[str], None] = 'f056e8abdc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('recordings', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('recordings', sa.Column('processing_status', sa.String(length=50), nullable=True))
    op.add_column('recordings', sa.Column('transcription_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'transcription_status')
    op.drop_column('recordings', 'processing_status')
    op.drop_column('recordings', 'mime_type')
    op.drop_column('recordings', 'file_size')
    # ### end Alembic commands ###
